import {StyleSheet} from 'react-native';
import colors from '../../constants/colors';

const styles = StyleSheet.create({
  mainView: {
    backgroundColor: colors.white,
    width: '100%',
    height: '100%',
  },
  taskDetails: {
    fontFamily: 'Poppins-Medium',
    fontSize: 20,
    color: colors.black,
  },
  taskDetailsView: {
    marginLeft: 30,
    marginTop: 10,
  },
  addTitle: {
    width: '90%',
    borderRadius: 20,
    borderColor: 'black',
    borderWidth: 1,
    height: 55,
    fontFamily: 'Poppins-Medium',
    fontSize: 20,
    color: 'black',
    justifyContent: 'center',
    paddingHorizontal: 30,
  },
  AddTitleView: {
    marginLeft: 20,
    marginTop: 10,
  },
  addDescription: {
    width: '90%',
    borderRadius: 20,
    borderColor: 'black',
    borderWidth: 1,
    height: 120,
    fontFamily: 'Poppins-Medium',
    fontSize: 20,
    color: 'black',
    justifyContent: 'center',
    paddingHorizontal: 30,
    marginTop: 20,
  },
  StatusContainer: {
    width: 70,
    height: 30,
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    marginTop: 5,
    borderBlockColor: colors.black,
    borderWidth: 1,
  },
  statusText: {
    color: colors.white,
  },
  priorityTypes: {
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-between',
  },
  mediumContainer: {
    width: 70,
    height: 30,
    backgroundColor: '#236454',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    marginTop: 5,
    borderBlockColor: colors.black,
    borderWidth: 1,
  },
  lowContainer: {
    width: 70,
    height: 30,
    backgroundColor: '#A6CE33',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    marginTop: 5,
    borderBlockColor: colors.black,
    borderWidth: 1,
  },
  todayText: {
    width: '45%',
    color: 'white',
    borderRadius: 20,
    alignItems: 'center',
    fontFamily: 'Poppins-Medium',
    fontSize: 16,
  },
  LaterTextButton: {
    width: '45%',
    backgroundColor: 'white',
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderBlockColor: 'black',
    borderWidth: 1,
  },
  timeContainer: {
    flexDirection: 'row',
    width: '70%',
    justifyContent: 'space-between',
    marginLeft: 30,
  },
  todayButton: {
    width: '45%',
    backgroundColor: 'black',
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  LaterText: {
    width: '45%',
    color: 'black',
    borderRadius: 20,
    alignItems: 'center',
    fontFamily: 'Poppins-Medium',
    fontSize: 16,
  },
  addButton: {
    width: '30%',
    backgroundColor: 'black',
    height: 50,
    borderRadius: 20,

    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    color: 'white',
    fontFamily: 'Poppins-Medium',
    fontSize: 20,
  },
  addbuttonView: {
    height: 50,

    marginTop: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
export default styles;
